[build]
  publish = "."

[[redirects]]
  from = "/oauth/gmc/callback"
  to = "https://syncstream.workers.dev/api/gmc-oauth-callback"
  status = 302
  force = true

[[redirects]]
  from = "/index"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
